# Auto-generated by qt-pods.
# This file should be put under version control.
TEMPLATE = subdirs
SUBDIRS = \
    jackcontrol

include(pods-subdirs.pri)

OTHER_FILES = \
  README.md \
  LICENSE \
  AUTHORS \
  TRANSLATORS \
  ChangeLog \
  INSTALL \
  manifest.json
